dependencies:
- name: jupyterhub
  version: "0.8-d462e1c"
  repository: 'https://jupyterhub.github.io/helm-chart/'
  import-values:
    - child: rbac
      parent: rbac
  # - name: pangeo
  #   version: v0.1.1-69b4a02
  #   repository: https://pangeo-data.github.io/helm-chart/
